# Generated by Django 5.0.6 on 2024-05-14 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Consumers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("EID", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=100)),
                ("driver_license", models.CharField(max_length=100)),
                ("drivers_expiry_date", models.DateField()),
                ("viechle_registration", models.CharField(max_length=100)),
            ],
        ),
    ]
