# Generated by Django 5.0.6 on 2024-05-14 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("MOI_Assistant", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="consumers",
            name="traffic_fine",
            field=models.CharField(default="No fines", max_length=100),
        ),
    ]
