# Generated by Django 5.0.6 on 2024-05-14 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("MOI_Assistant", "0002_consumers_traffic_fine"),
    ]

    operations = [
        migrations.RenameField(
            model_name="consumers",
            old_name="viechle_registration",
            new_name="vehicle_registration",
        ),
        migrations.AddField(
            model_name="consumers",
            name="criminal_record_certificate",
            field=models.CharField(default="No criminal record", max_length=100),
        ),
    ]
